[DEV01]
#Lifeary
Dev01LiferayAServer    ansible_ssh_host=165.22.45.221   ansible_connection=ssh   ansible_user=sdasari
Dev01LiferayMServer1   ansible_ssh_host=165.22.45.221   ansible_connection=ssh   ansible_user=sdasari
Dev01LiferayMServer2   ansible_ssh_host=67.205.176.89   ansible_connection=ssh   ansible_user=sdasari

[Aserver]
Dev01LiferayAServer

[Mserver]
Dev01LiferayMServer1
Dev01LiferayMServer2

[DEV01:vars]
deploy_user=oracle
mi_user=sdasari
baseDir=/u01/app/oracle
ansible_become_user=oracle
ansible_become_method=sudo
ansible_become_pass= "{{ vault_sdasari_sudo_password }}"
weblogicUser= weblogic
weblogicPass= "{{ vault_weblogic_pass }}"
domainDir= /u01/app/oracle/Middleware/Oracle_Home/user_projects/domains/base_domain
wlsDir= /u01/app/oracle/Middleware/Oracle_Home/wlserver/server
